-- Y Access UI. Generated by tools/build.mjs. Presentation only.
local Modules, Loaded = {}, {}
Modules["Theme"] = function(require)
--//Variables
local Theme = {
	Background = Color3.fromRGB(12, 11, 15),
	Surface = Color3.fromRGB(24, 18, 26),
	Border = Color3.fromRGB(48, 38, 49),
	Text = Color3.fromRGB(243, 239, 243),
	Muted = Color3.fromRGB(170, 161, 174),
	Accent = Color3.fromRGB(112, 18, 67),
	Pink = Color3.fromRGB(237, 132, 185),
	Success = Color3.fromRGB(172, 211, 194),
	Error = Color3.fromRGB(244, 157, 167),
}

return Theme

end

Modules["Surface"] = function(require)
local Theme = require("./Theme")

--//Variables
local Surface = {}

--//Source
function Surface.Create(Class, Properties, Parent)
	local Object = Instance.new(Class)
	for Name, Value in pairs(Properties) do Object[Name] = Value end
	Object.Parent = Parent
	return Object
end

function Surface.Config(Options, Name)
	local Config = table.clone(Options or {})
	Config.Name = Config.Name or Name
	Config.Theme = setmetatable(table.clone(Config.Theme or {}), { __index = Theme })
	return Config
end

function Surface.Mount(Gui)
	local function Mount(Parent)
		if typeof(Parent) ~= "Instance" then return false end
		return pcall(function()
			local Previous = Parent:FindFirstChild(Gui.Name)
			if Previous then Previous:Destroy() end
			Gui.Parent = Parent
		end)
	end
	local Success, Hidden = pcall(function() return type(gethui) == "function" and gethui() end)
	if Success and Mount(Hidden) then return end
	if Mount(game:GetService("CoreGui")) then return end
	local Player = game:GetService("Players").LocalPlayer
	assert(Player and Mount(Player:WaitForChild("PlayerGui", 5)), "Y Hub UI is unavailable")
end

function Surface.Animate(Object, Properties, Duration)
	local Tween = game:GetService("TweenService"):Create(Object,
		TweenInfo.new(Duration or 0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), Properties)
	Tween:Play()
	return Tween
end

return Surface

end

Modules["Access"] = function(require)
local Surface = require("./Surface")

--//Variables
local View = {}
View.__index = View
local Checked = utf8.char(10003)

local Create = Surface.Create

--//Source
function View.new(Config)
	Config = Surface.Config(Config, "YHubAccess")
	local self = setmetatable({ Config = Config, Connections = {}, Remember = true, ContentHeight = 358 }, View)
	local Success = pcall(self.Build, self)
	if not Success then
		self:Destroy()
		error("Y Hub access UI is unavailable", 0)
	end
	return self
end

function View:Build()
	local Config = self.Config
	local Theme = Config.Theme
	local Input = game:GetService("UserInputService")
	local Gui = Create("ScreenGui", {
		Name = Config.Name, ResetOnSpawn = false, DisplayOrder = 10000,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling, ScreenInsets = Enum.ScreenInsets.CoreUISafeInsets,
	})
	self.Gui = Gui
	Surface.Mount(Gui)

	local Backdrop = Create("Frame", {
		Name = "Layout", Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1, BorderSizePixel = 0, Active = false,
	}, Gui)
	local Panel = Create("Frame", {
		Name = "Panel", AnchorPoint = Vector2.new(0.5, 0.5), Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(400, self.ContentHeight), BackgroundColor3 = Theme.Background, BorderSizePixel = 0,
		ClipsDescendants = true, Active = true,
	}, Backdrop)
	Create("UICorner", { CornerRadius = UDim.new(0, 4) }, Panel)
	Create("UIStroke", { Color = Theme.Border, Thickness = 1 }, Panel)
	Create("Frame", { Name = "Accent", Size = UDim2.new(1, 0, 0, 2), BackgroundColor3 = Theme.Accent, BorderSizePixel = 0 }, Panel)
	local Scroll = Create("ScrollingFrame", {
		Name = "Content", Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1, BorderSizePixel = 0, ScrollBarThickness = 3,
		ScrollBarImageColor3 = Theme.Pink, CanvasSize = UDim2.fromOffset(0, self.ContentHeight),
		ScrollingDirection = Enum.ScrollingDirection.Y,
	}, Panel)

	local function Label(Name, Text, X, Y, Width, Height, Size, Color, Font)
		return Create("TextLabel", {
			Name = Name, Text = Text, Position = UDim2.fromOffset(X, Y), Size = Width < 0 and UDim2.new(1, Width, 0, Height) or UDim2.fromOffset(Width, Height),
			BackgroundTransparency = 1, TextColor3 = Color or Theme.Text, TextSize = Size or 14,
			Font = Font or Enum.Font.Gotham, TextXAlignment = Enum.TextXAlignment.Left,
			TextWrapped = true, RichText = false,
		}, Scroll)
	end
	local function Button(Name, Text, Position, Size, Background, Color)
		local Object = Create("TextButton", {
			Name = Name, Text = Text, Position = Position, Size = Size,
			BackgroundColor3 = Background, TextColor3 = Color or Theme.Text,
			Font = Enum.Font.GothamMedium, TextSize = 14, BorderSizePixel = 0,
			AutoButtonColor = true, Selectable = true,
		}, Scroll)
		Create("UICorner", { CornerRadius = UDim.new(0, 4) }, Object)
		return Object
	end

	local Mark = Label("Mark", "<i>Y</i>", 24, 22, 30, 33, 24, Theme.Text, Enum.Font.GothamBold)
	Mark.RichText = true
	Mark.BackgroundTransparency, Mark.BackgroundColor3, Mark.TextXAlignment = 0, Theme.Accent, Enum.TextXAlignment.Center
	Label("Brand", "Y HUB.", 64, 22, 150, 33, 22, Theme.Text, Enum.Font.GothamBold)
	local Close = Button("Close", utf8.char(215), UDim2.new(1, -60, 0, 14), UDim2.fromOffset(44, 44), Theme.Background, Theme.Muted)
	Close.TextSize = 22
	Create("Frame", {
		Name = "HeaderLine", Position = UDim2.fromOffset(0, 76), Size = UDim2.new(1, 0, 0, 1),
		BackgroundColor3 = Theme.Border, BorderSizePixel = 0,
	}, Scroll)

	local Field = Create("Frame", {
		Name = "KeyField", Position = UDim2.fromOffset(24, 96), Size = UDim2.new(1, -48, 0, 48),
		BackgroundColor3 = Theme.Surface, BorderSizePixel = 0,
	}, Scroll)
	Create("UICorner", { CornerRadius = UDim.new(0, 4) }, Field)
	local FieldBorder = Create("UIStroke", { Color = Theme.Border, Thickness = 1 }, Field)
	local Key = Create("TextBox", {
		Name = "Key", Position = UDim2.fromOffset(13, 0), Size = UDim2.new(1, -26, 1, 0),
		Text = "", PlaceholderText = "Access key", ClearTextOnFocus = false,
		BackgroundTransparency = 1, TextColor3 = Theme.Text, PlaceholderColor3 = Theme.Muted,
		TextSize = 14, Font = Enum.Font.Gotham, TextXAlignment = Enum.TextXAlignment.Left,
		TextTransparency = 0, MultiLine = false,
	}, Field)
	self.Key = Key

	local function Check(Name, Text, Position, Width)
		local Toggle = Button(Name, "", Position, UDim2.new(0.5, Width, 0, 42), Theme.Background)
		local Box = Create("Frame", {
			Name = "Box", Position = UDim2.fromOffset(0, 13), Size = UDim2.fromOffset(18, 18),
			BackgroundColor3 = Theme.Surface, BorderSizePixel = 0,
		}, Toggle)
		Create("UICorner", { CornerRadius = UDim.new(0, 3) }, Box)
		Create("UIStroke", { Color = Theme.Border, Thickness = 1 }, Box)
		local Tick = Create("TextLabel", {
			Name = "Tick", Text = "", Size = UDim2.fromScale(1, 1), BackgroundTransparency = 1,
			TextColor3 = Theme.Pink, TextSize = 14, Font = Enum.Font.GothamBold,
		}, Box)
		local TextLabel = Create("TextLabel", {
			Name = "Label", Text = Text, Position = UDim2.fromOffset(26, 0), Size = UDim2.new(1, -26, 1, 0),
			BackgroundTransparency = 1, TextColor3 = Theme.Muted, TextSize = 12,
			Font = Enum.Font.Gotham, TextXAlignment = Enum.TextXAlignment.Left, TextWrapped = true,
		}, Toggle)
		return Toggle, Tick, TextLabel
	end
	local Remember, RememberTick, RememberLabel = Check("Remember", "Remember key", UDim2.fromOffset(24, 146), -24)
	Remember.Size = UDim2.new(1, -48, 0, 44)
	self.RememberButton, self.RememberTick, self.RememberLabel = Remember, RememberTick, RememberLabel
	RememberTick.Text = Checked
	self.Status = Label("Status", "", 24, 244, -48, 40, 12, Theme.Muted)
	self.Status.Visible = false
	self.Continue = Button("Continue", "Continue", UDim2.fromOffset(24, 192), UDim2.new(1, -48, 0, 44), Theme.Accent)
	self.Continue.Modal = true
	self.DiscordDivider = Create("Frame", {
		Name = "DiscordDivider", Position = UDim2.fromOffset(24, 252), Size = UDim2.new(1, -48, 0, 1),
		BackgroundColor3 = Theme.Border, BorderSizePixel = 0,
	}, Scroll)
	self.DiscordHint = Label("DiscordHint", "Get your key on Discord", 24, 264, -48, 20, 12, Theme.Muted)
	self.DiscordHint.TextXAlignment = Enum.TextXAlignment.Center
	local Discord = Button("Discord", "Copy invite", UDim2.new(0.5, 0, 0, 294), UDim2.fromOffset(180, 44), Theme.Surface, Theme.Pink)
	Discord.AnchorPoint = Vector2.new(0.5, 0)
	Discord.TextSize = 13
	Discord.TextXAlignment = Enum.TextXAlignment.Center
	Create("UIStroke", { Color = Theme.Accent, Thickness = 1, ApplyStrokeMode = Enum.ApplyStrokeMode.Border }, Discord)
	self.Discord = Discord
	self.Scroll, self.Panel, self.Backdrop, self.Input = Scroll, Panel, Backdrop, Input

	local function Connect(Signal, Callback)
		table.insert(self.Connections, Signal:Connect(Callback))
	end
	local function Submit()
		if self.OnSubmit and not self.Busy then self.OnSubmit(Key.Text, self.Remember) end
	end
	Connect(Key.Focused, function()
		FieldBorder.Color = Theme.Pink
		self:Resize()
	end)
	Connect(Key.FocusLost, function(Enter)
		FieldBorder.Color = Theme.Border
		if Enter then Submit() end
	end)
	Connect(Key.ReturnPressedFromOnScreenKeyboard, Submit)
	Connect(self.Continue.Activated, Submit)
	Connect(Close.Activated, function() if self.OnClose then self.OnClose() end end)
	Connect(Remember.Activated, function()
		if self.Busy or not self.CanRemember then return end
		self.Remember = not self.Remember
		RememberTick.Text = self.Remember and Checked or ""
	end)
	Connect(Discord.Activated, function()
		if self.InviteCopied then return end
		local Success = type(setclipboard) == "function" and pcall(setclipboard, Config.Discord or "")
		if not Success then self:SetStatus(Config.Discord or "Discord invite unavailable.", "muted") return end
		self.InviteCopied = true
		Discord.Text, Discord.TextColor3 = "Invite copied", Theme.Success
		task.delay(2, function()
			if self.Destroyed then return end
			self.InviteCopied = false
			Discord.Text, Discord.TextColor3 = "Copy invite", Theme.Pink
		end)
	end)
	local function Resize()
		self:Resize()
	end
	Connect(Backdrop:GetPropertyChangedSignal("AbsoluteSize"), Resize)
	Connect(Backdrop:GetPropertyChangedSignal("AbsolutePosition"), Resize)
	Connect(Input:GetPropertyChangedSignal("OnScreenKeyboardVisible"), Resize)
	Connect(Input:GetPropertyChangedSignal("OnScreenKeyboardPosition"), Resize)
	Connect(Input:GetPropertyChangedSignal("OnScreenKeyboardSize"), Resize)
	Connect(Gui.Destroying, function()
		self:Disconnect()
		self.Destroyed = true
		if self.OnClose then self.OnClose() end
	end)
	Resize()
end

function View:Resize()
	if self.Destroyed then return end
	local Size = self.Backdrop.AbsoluteSize
	if Size.X < 1 or Size.Y < 1 then return end
	local Height = Size.Y
	if self.Input.OnScreenKeyboardVisible then
		local KeyboardTop = self.Input.OnScreenKeyboardPosition.Y - self.Backdrop.AbsolutePosition.Y
		if KeyboardTop <= 0 then KeyboardTop = Size.Y - self.Input.OnScreenKeyboardSize.Y end
		if KeyboardTop > 0 then Height = math.min(Height, KeyboardTop) end
	end
	local PanelHeight = math.min(self.ContentHeight, math.max(1, Height - 24))
	self.Panel.Size = UDim2.fromOffset(math.min(400, math.max(1, Size.X - 32)), PanelHeight)
	self.Panel.Position = UDim2.new(0.5, 0, 0, Height * 0.5)
	self.Scroll.CanvasSize = UDim2.fromOffset(0, self.ContentHeight)
	if self.Key:IsFocused() then
		self.Scroll.CanvasPosition = Vector2.new(0, math.max(0, 156 - PanelHeight))
	else
		self.Scroll.CanvasPosition = Vector2.new(0, math.min(self.Scroll.CanvasPosition.Y, math.max(0, self.ContentHeight - PanelHeight)))
	end
end

function View:Bind(OnSubmit, OnClose)
	self.OnSubmit, self.OnClose = OnSubmit, OnClose
end

function View:SetRememberAvailable(Available)
	self.CanRemember, self.Remember = Available == true, Available == true
	self.RememberTick.Text = self.Remember and Checked or ""
	self.RememberLabel.Text = Available and "Remember key" or "Saving unavailable"
end

function View:SetBusy(Busy, Label)
	if self.Destroyed then return end
	self.Busy = Busy
	self.Key.TextEditable = not Busy
	self.Continue.Text = Label or (Busy and "Checking..." or "Continue")
	self.Continue.AutoButtonColor = not Busy
	self.Continue.BackgroundColor3 = Busy and self.Config.Theme.Surface or self.Config.Theme.Accent
end

function View:SetStatus(Text, Tone)
	if self.Destroyed then return end
	local Colors = { error = self.Config.Theme.Error, success = self.Config.Theme.Success, muted = self.Config.Theme.Muted }
	self.Status.Text, self.Status.TextColor3 = Text, Colors[Tone] or Colors.muted
	self.Status.Visible = #Text > 0
	local Offset = self.Status.Visible and 52 or 0
	self.ContentHeight = 358 + Offset
	self.DiscordDivider.Position = UDim2.fromOffset(24, 252 + Offset)
	self.DiscordHint.Position = UDim2.fromOffset(24, 264 + Offset)
	self.Discord.Position = UDim2.new(0.5, 0, 0, 294 + Offset)
	self:Resize()
end

function View:ClearKey()
	if not self.Destroyed then self.Key.Text = "" end
end

function View:Disconnect()
	for _, Connection in ipairs(self.Connections) do Connection:Disconnect() end
	table.clear(self.Connections)
end

function View:Destroy()
	if self.Destroyed then return end
	self.Destroyed = true
	self:Disconnect()
	if self.Key then self.Key.Text = "" end
	if self.Gui then self.Gui:Destroy() end
end

return View

end

Modules["Progress"] = function(require)
local Surface = require("./Surface")

--//Variables
local Progress = {}
Progress.__index = Progress
local Create = Surface.Create

--//Source
function Progress.new(Options)
	local self = setmetatable({ Config = Surface.Config(Options, "YHubStartup"), Connections = {}, Tweens = {}, Steps = {} }, Progress)
	local Success, Message = pcall(self.Build, self)
	if not Success then self:Destroy() error(Message, 0) end
	return self
end

function Progress:Connect(Signal, Callback)
	self.Connections[#self.Connections + 1] = Signal:Connect(Callback)
end

function Progress:Animate(Key, Object, Properties, Duration)
	if self.Tweens[Key] then self.Tweens[Key]:Cancel() end
	self.Tweens[Key] = Surface.Animate(Object, Properties, Duration)
end

function Progress:Build()
	local Theme = self.Config.Theme
	local Gui = Create("ScreenGui", {
		Name = self.Config.Name, ResetOnSpawn = false, DisplayOrder = 10001,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling, ScreenInsets = Enum.ScreenInsets.CoreUISafeInsets,
	})
	self.Gui = Gui
	Surface.Mount(Gui)
	self.Layout = Create("Frame", { Name = "Layout", Size = UDim2.fromScale(1, 1), BackgroundTransparency = 1 }, Gui)
	local Panel = Create("CanvasGroup", {
		Name = "Panel", AnchorPoint = Vector2.new(0.5, 1), Position = UDim2.new(0.5, 0, 1, -20),
		Size = UDim2.fromOffset(380, 206), BackgroundColor3 = Theme.Background, BorderSizePixel = 0,
		GroupTransparency = 1,
	}, self.Layout)
	self.Panel = Panel
	Create("UICorner", { CornerRadius = UDim.new(0, 6) }, Panel)
	Create("UIStroke", { Color = Theme.Border, Thickness = 1 }, Panel)
	self.Scroll = Create("ScrollingFrame", {
		Name = "Content", Size = UDim2.fromScale(1, 1), BackgroundTransparency = 1, BorderSizePixel = 0,
		CanvasSize = UDim2.fromOffset(0, 206), ScrollBarThickness = 2,
		ScrollBarImageColor3 = Theme.Pink, ScrollingDirection = Enum.ScrollingDirection.Y,
	}, Panel)
	local function Label(Name, Text, Position, Size, TextSize, Color, Font)
		return Create("TextLabel", {
			Name = Name, Text = Text, Position = Position, Size = Size, BackgroundTransparency = 1,
			TextColor3 = Color, Font = Font or Enum.Font.Gotham, TextSize = TextSize,
			TextXAlignment = Enum.TextXAlignment.Left, TextWrapped = true,
		}, self.Scroll)
	end
	local Mark = Label("Mark", "<i>Y</i>", UDim2.fromOffset(18, 17), UDim2.fromOffset(30, 30), 22, Theme.Text, Enum.Font.GothamBold)
	Mark.RichText, Mark.BackgroundTransparency, Mark.BackgroundColor3, Mark.TextXAlignment = true, 0, Theme.Accent, Enum.TextXAlignment.Center
	Label("Brand", "Y HUB.", UDim2.fromOffset(59, 17), UDim2.new(1, -110, 0, 30), 17, Theme.Text, Enum.Font.GothamBold)
	local Close = Create("TextButton", {
		Name = "Close", Text = utf8.char(215), Position = UDim2.new(1, -50, 0, 8), Size = UDim2.fromOffset(44, 44),
		BackgroundTransparency = 1, TextColor3 = Theme.Muted, TextSize = 23, Font = Enum.Font.Gotham,
	}, self.Scroll)
	self.Title = Label("Title", "Checking compatibility", UDim2.fromOffset(18, 61), UDim2.new(1, -36, 0, 24), 15, Theme.Text, Enum.Font.GothamMedium)
	self.Message = Label("Message", "Preparing your session...", UDim2.fromOffset(18, 91), UDim2.new(1, -36, 0, 40), 12, Theme.Muted)
	self.Message.TextYAlignment = Enum.TextYAlignment.Top
	for Index, Name in ipairs({ "Environment", "Functions", "Hooks" }) do
		local Row = Create("Frame", {
			Name = Name, Position = UDim2.new((Index - 1) / 3, 18 - (Index - 1) * 12, 0, 150),
			Size = UDim2.new(1 / 3, -20, 0, 37), BackgroundTransparency = 1,
		}, self.Scroll)
		local Track = Create("Frame", { Name = "Track", Size = UDim2.new(1, 0, 0, 3), BackgroundColor3 = Theme.Border, BorderSizePixel = 0 }, Row)
		local Fill = Create("Frame", { Name = "Fill", Size = UDim2.fromScale(0, 1), BackgroundColor3 = Theme.Pink, BorderSizePixel = 0 }, Track)
		local Caption = Create("TextLabel", {
			Name = "Caption", Text = Name, Position = UDim2.fromOffset(0, 11), Size = UDim2.new(1, 0, 0, 22),
			BackgroundTransparency = 1, TextColor3 = Theme.Muted, TextSize = 11, Font = Enum.Font.Gotham,
			TextXAlignment = Enum.TextXAlignment.Left,
		}, Row)
		self.Steps[Index] = { Fill = Fill, Caption = Caption }
	end
	self:Connect(Close.Activated, function() self:Destroy() end)
	self:Connect(self.Layout:GetPropertyChangedSignal("AbsoluteSize"), function() self:Resize() end)
	self:Connect(Gui.Destroying, function() self:Destroy() end)
	self:Resize()
	self:Animate("Entrance", Panel, { GroupTransparency = 0 }, 0.25)
end

function Progress:Resize()
	if self.Destroyed then return end
	local Size = self.Layout.AbsoluteSize
	if Size.X < 1 or Size.Y < 1 then return end
	self.Panel.Size = UDim2.fromOffset(math.min(380, math.max(1, Size.X - 24)), math.min(206, math.max(1, Size.Y - 32)))
end

function Progress:SetStage(Index, Message)
	if self.Destroyed then return end
	self.Message.Text = Message
	for StepIndex, Step in ipairs(self.Steps) do
		local Complete = StepIndex < Index
		Step.Caption.TextColor3 = StepIndex == Index and self.Config.Theme.Text or self.Config.Theme.Muted
		self:Animate(StepIndex, Step.Fill, { Size = UDim2.fromScale(Complete and 1 or StepIndex == Index and 0.3 or 0, 1) })
	end
end

function Progress:SetResult(Success, Message)
	if self.Destroyed then return end
	self.Title.Text = Success and "Ready to continue" or "Executor not supported"
	self.Title.TextColor3 = Success and self.Config.Theme.Success or self.Config.Theme.Error
	self.Message.Text = Message
	if Success then
		for Index, Step in ipairs(self.Steps) do
			Step.Fill.BackgroundColor3 = self.Config.Theme.Success
			self:Animate(Index, Step.Fill, { Size = UDim2.fromScale(1, 1) })
		end
	end
end

function Progress:Dismiss()
	if self.Destroyed then return false end
	self:Animate("Entrance", self.Panel, { GroupTransparency = 1 }, 0.18)
	task.wait(0.18)
	if self.Destroyed then return false end
	self:Destroy()
	return true
end

function Progress:Destroy()
	if self.Destroyed then return end
	self.Destroyed = true
	for _, Connection in ipairs(self.Connections) do Connection:Disconnect() end
	for _, Tween in pairs(self.Tweens) do Tween:Cancel() end
	table.clear(self.Connections)
	table.clear(self.Tweens)
	if self.Gui then self.Gui:Destroy() end
end

return Progress

end

Modules["init"] = function(require)
local Access = require("./Access")
local Progress = require("./Progress")

return {
	Version = "1.0.0",
	CreateAccess = Access.new,
	CreateProgress = Progress.new,
}

end

local function Import(Path)
	local Name = string.gsub(Path, "^%./", "")
	if Loaded[Name] == nil then Loaded[Name] = assert(Modules[Name], "Unknown UI module")(Import) end
	return Loaded[Name]
end
return Import("init")
