import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const modules = ['Theme', 'Surface', 'Access', 'Progress', 'init'];
const source = modules.map((name) => `Modules[${JSON.stringify(name)}] = function(require)\n${readFileSync(path.join(root, 'src', `${name}.lua`), 'utf8')}\nend`).join('\n\n');
writeFileSync(path.join(root, 'Library.lua'), `-- Y Access UI. Generated by tools/build.mjs. Presentation only.\nlocal Modules, Loaded = {}, {}\n${source}\n\nlocal function Import(Path)\n\tlocal Name = string.gsub(Path, "^%./", "")\n\tif Loaded[Name] == nil then Loaded[Name] = assert(Modules[Name], "Unknown UI module")(Import) end\n\treturn Loaded[Name]\nend\nreturn Import("init")\n`);
console.log('Built Library.lua');
